version: '3'

networks:
  api2_network:
    driver: bridge

services:
  php-fpm:
    image: my-php-fpm-image
    environment:
      DB_HOST: mysql
    ports:
      - "9000" # Expose port 9000
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/API2
    networks:
      - api2_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.34-debian
    #    proveri mapiranje portova
    environment:
      MYSQL_ROOT_PASSWORD: Sifra123!
      MYSQL_DATABASE: api_database
      MYSQL_USER: katarinakat
      MYSQL_PASSWORD: Sifra123!
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - api2_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8087:80"
    environment:
      PMA_HOST: mysql
    networks:
      - api2_network

  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - api2_network

volumes:
  mysql: